[workspace]
members = [
    # "2015/d*",
    # "2016/d*",
    # "2017/d*",
    # "2018/d*",
    "2019/d*",
    "2020/d*",
    "2021/d*",
    "2022/d*",
    "2023/d*",
    "2024/d*",
    "2025/d*",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2021"
